import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  const algorithms = [
    "SIDH",
    "Kyber",
    "Dilithium",
    "Falcon",
  ]
  return (
    <>
      <Head>
        <title>Kuantun Kompare</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen overflow-scroll snap-y snap-mandatory scroll-smooth flex">
        <div className="flex flex-col w-80 h-full bg-gray-100 px-8 py-12 text-center" style={
          {
            background: "linear-gradient(335deg,rgba(98,211,213,.576),rgba(235,164,244,.383) 51%,rgba(255,237,197,.865))",
          }
        }>
          {
            algorithms.map((algorithm, index) => (
              <Link href={`/${algorithm}`} key={index} className="text-2xl font-bold text-gray-800 hover:text-gray-900 py-1 my-4 rounded-lg border border-gray-900 bg-white border-solid">
                {algorithm}
              </Link>
            ))
          }
        </div>

      </main>
    </>
  );
};

export default Home;
